#!/usr/bin/env ruby
# frozen_string_literal: true

root = File.expand_path('..', __dir__)
Dir.chdir root

port = ARGV[0] || 4000

pid = fork do
  $stderr.reopen '/dev/null' # silence WEBrick output
  exec 'bundle', 'exec', 'rackup', '-p', port.to_s
end
sleep 1

status = system(
  "npm test -- http://localhost:#{port}/test/qunit.html"
)

Process.kill 'SIGINT', pid
Process.wait pid

exit status
